name: Daily Financial Data Sync

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas yfinance google-cloud-bigquery pandas-gbq db-dtypes dbt-bigquery

      - name: Authenticate to Google Cloud
        shell: bash
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcp_key.json" >> $GITHUB_ENV

      - name: Run Daily Price Extraction
        run: python extraction/daily_update.py

      

      - name: Run dbt transformation
        env:
        
          DBT_KEYFILE: ${{ github.workspace }}/gcp_key.json
        run: |
          
          mkdir -p ~/.dbt
          
         
          cat <<EOF > ~/.dbt/profiles.yml
          market_pipeline:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: financial-market-analysis
                dataset: analytics_finance
                threads: 4
                keyfile: $DBT_KEYFILE
                priority: interactive
          EOF
          
          